analyzer:
  language:
    strict-casts: true
    strict-inference: true
  exclude:
    - example/**
    - test/**

    - lib/src/hardware_profiler.dart
    - lib/src/hardware_profiler_stub.dart
linter:
  rules:
    - prefer_const_constructors
    - prefer_final_locals
